name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install -r requirements.txt

      - name: Install docker-compose if macOs
        if: matrix.os == 'macos-latest'
        run: brew install docker-compose
        
      - name: Start containers
        run: |
          docker-compose -f docker-compose-dev.yml up airflow-init
          docker-compose -f docker-compose-dev.yml up -d

      - name: Test with tox
        run: tox
