name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install -r requirements_dev.txt

      - name: Test with mypy
        run: mypy src

      - name: Test with flake8
        run: flake8 src

      - name: Test with tox
        run: tox
        
      # need to write tests first
      # - name: Test and generate coverage report with pytest
      #   run: pytest --cov=./ --cov-report=xml

      - name: Start containers
        run: |
          mkdir -p ./logs ./plugins
          echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
          chmod 755 ./dags ./logs ./plugins
          docker-compose up --build airflow-init
          docker-compose up --build -d

      # - name: Run Airflow pipeline
      #   run: how to? with docker exec?